// apps/project3-react/src/App.tsx
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import { sum } from "@project-survey/utils";
import { sum as sum2 } from "@project-survey/utils2";

function App() {
  const [count, setCount] = useState(0);

  return (
    <>
      <div>
        <h1>{sum(1, 1)}</h1>
        <h1>{sum2(1, 1)}</h1>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount(count => count + 1)}>count is {count}</button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">Click on the Vite and React logos to learn more</p>
    </>
  );
}

export default App;

// apps/project6-solid/src/App.tsx
import { createSignal } from "solid-js";
import MyComponent from "./study/show";
import MyClick from "./study/click";

function App() {
  const [count, setCount] = createSignal(0);

  return (
    <>
      <h1>Vite + Solid</h1>
      <div class="card red">
        <button onClick={() => setCount(count => count + 1)}>count is {count()}</button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <MyComponent></MyComponent>
      <MyClick></MyClick>
    </>
  );
}

export default App;
